// Copyright 2025 Enactic, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  topSidebar: [{type: 'autogenerated', dirName: '.'}],

  gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
  hardwareSidebar: [{type: 'autogenerated', dirName: 'hardware'}],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  teleopSidebar: [{type: 'autogenerated', dirName: 'teleop'}],
  simulationSidebar: [{type: 'autogenerated', dirName: 'simulation'}],
  purchaseSidebar: [{type: 'autogenerated', dirName: 'purchase'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
