planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/ResolveConstraintFrames
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
start_state_max_bounds_error: 0.1
planner_configs:
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
    border_fraction: 0.9  # 聚焦边界的时间比例。默认 0.9
    min_valid_path_fraction: 0.5  # 接受部分有效移动的阈值比例。默认 0.5
  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
    goal_bias: 0.05  # 当靠近目标时选择目标的概率。默认 0.05
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
    goal_bias: 0.05  # 当靠近目标时选择目标的概率。默认 0.05
    delay_collision_checking: 1  # 找到无碰撞父节点后立即停止碰撞检查。默认 1
  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
    goal_bias: 0.05  # 当靠近目标时选择目标的概率。默认 0.05
    max_states_failed: 10  # 何时开始提高温度的失败次数阈值。默认 10
    temp_change_factor: 2.0  # 温度增加或降低的因子。默认 2.0
    min_temperature: 10e-10  # 温度变化的下限。默认 10e-10
    init_temperature: 10e-6  # 初始温度。默认 10e-6
    frountier_threshold: 0.0  # 新状态与最近邻居的距离阈值，用于取消前沿资格。默认0.0
    frountierNodeRatio: 0.1  # 1/10，即每10个前沿节点对应1个非前沿节点。默认 0.1
    k_constant: 0.0  # 用于标准化表达式的值。默认 0.0，并在setup()中设置
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10  # 使用的k个最近邻居数。默认 10
  PRMstarkConfigDefault:
    type: geometric::PRMstar
  LBTRRTkConfigDefault:
    type: geometric::LBTRRT
    range: 0.0  # 添加到树中的最大运动距离。默认 0.0
    goal_bias: 0.05  # 当靠近目标时选择目标的概率。默认 0.05
    epsilon: 0.4  # 最优性近似因子。默认 0.4
    temp_change_factor: 0.1  # 温度增加或降低的因子。默认 0.1
  TrajOptDefault:
    type: geometric::TrajOpt
 
upper_body:
  planner_configs:
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - LBTRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - TrajOptDefault

left_arm:
  planner_configs:
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - LBTRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - TrajOptDefault

right_arm:
  planner_configs:
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - LBTRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - TrajOptDefault

left_side:
  planner_configs:
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - LBTRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - TrajOptDefault    

right_side:
  planner_configs:
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - LBTRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - TrajOptDefault